# Generated by Django 5.0.6 on 2025-01-18 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musicapp', '0001_initial'),
        ('singerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singerapp.singer'),
        ),
        migrations.AddField(
            model_name='music',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicapp.album'),
        ),
        migrations.AddField(
            model_name='music',
            name='genre',
            field=models.ManyToManyField(blank=True, to='musicapp.genre'),
        ),
        migrations.AddField(
            model_name='music',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singerapp.singer'),
        ),
    ]
