# Generated by Django 5.0.6 on 2025-01-20 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musicapp', '0005_alter_music_album'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('private', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.userprofile')),
            ],
            options={
                'permissions': [('all_playlist_perms', 'Full access to playlists'), ('get_playlist', 'View playlist'), ('add_music', 'Add music to playlist'), ('remove_music', 'Remove music from playlist')],
            },
        ),
        migrations.CreateModel(
            name='PlaylistMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.music')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlistapp.playlist')),
            ],
            options={
                'unique_together': {('playlist', 'music')},
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='music',
            field=models.ManyToManyField(blank=True, related_name='songs_with_count', through='playlistapp.PlaylistMusic', to='musicapp.music'),
        ),
    ]
