# Generated by Django 5.0.6 on 2025-01-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='listens',
            field=models.IntegerField(default=0),
        ),
    ]
