# Generated by Django 5.0.6 on 2025-01-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlistapp', '0002_playlist_listens'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'permissions': [('all_playlist_perms', 'Full access to playlists'), ('get_playlist', 'View playlist'), ('add_music', 'Add music to playlist'), ('remove_music', 'Remove music from playlist'), ('set_playlist_perms', 'Update playlist permissions'), ('remove_playlist_perms', 'Remove playlist permissions')]},
        ),
    ]
